// TODO Move to Test
export const lectures = [
  { title: 'セクション１', kind: 'section' },
  {
    order: 1,
    title: 'レクチャーA',
    kind: 'lecture',
    duration: 30,
    isCompleted: true,
    type: 'VideoLecture',
  },
  {
    order: 2,
    title: 'レクチャーB',
    kind: 'lecture',
    duration: 60,
    isCompleted: true,
    type: 'VideoLecture',
  },
  {
    order: 3,
    title: 'レクチャーC',
    kind: 'lecture',
    duration: 90,
    isCompleted: true,
    type: 'VideoLecture',
  },
  { title: 'セクション2', kind: 'section' },
  {
    order: 4,
    title: 'レクチャーD',
    kind: 'lecture',
    duration: 30,
    isCompleted: false,
    type: 'VideoLecture',
  },
  {
    order: 5,
    title: 'レクチャーE',
    kind: 'lecture',
    duration: 60,
    isCompleted: false,
    type: 'VideoLecture',
  },
  {
    order: 6,
    title: 'レクチャーF',
    kind: 'lecture',
    duration: 90,
    isCompleted: false,
    type: 'VideoLecture',
  },
  { title: 'セクション3', kind: 'section' },
  {
    order: 7,
    title: 'レクチャーG',
    kind: 'lecture',
    duration: 30,
    isCompleted: false,
    type: 'VideoLecture',
  },
  {
    order: 8,
    title: 'レクチャーH',
    kind: 'lecture',
    duration: 60,
    isCompleted: false,
    type: 'VideoLecture',
  },
  {
    order: 9,
    title: 'レクチャーI',
    kind: 'lecture',
    duration: 90,
    isCompleted: false,
    type: 'VideoLecture',
  },
  { title: 'セクション4', kind: 'section' },
  {
    order: 10,
    title: 'レクチャーJ',
    kind: 'lecture',
    duration: 30,
    isCompleted: false,
    type: 'VideoLecture',
  },
  {
    order: 11,
    title: 'レクチャーK',
    kind: 'lecture',
    duration: 60,
    isCompleted: false,
    type: 'VideoLecture',
  },
  {
    order: 12,
    title: 'レクチャーL',
    kind: 'lecture',
    duration: 90,
    isCompleted: false,
    type: 'VideoLecture',
  },
];

export const course = {
  title: '差がつくビジネス戦略講座 | 事業開発・Platform戦略(R)・ITマーケティング',
  lectures,
};
