extends: airbnb

parser: babel-eslint

parserOptions:
  ecmaFeatures:
  jsx: true

plugins:
  - react
  - jsx-a11y
  - import
  - flowtype

rules:
  # Enable
  no-unused-vars: [
    "error",
    { "varsIgnorePattern": "[iI]gnored" }
  ]
  #  flowtype/define-flow-type: 1
  #  flowtype/use-flow-type: 1
  #  flowtype/require-parameter-type: 1
  #  flowtype/require-return-type: [
  #    1,
  #    "always",
  #    {
  #      annotateUndefined: "never"
  #    }
  #  ]
  #  flowtype/space-after-type-colon: [
  #    1,
  #    "always"
  #  ]
  #  flowtype/space-before-type-colon: [
  #    1,
  #    "never"
  #  ]
  #  flowtype/type-id-match: [
  #    1,
  #    "^([A-Z][a-z0-9]+)+Type$"
  #  ]
  #  flowtype/valid-syntax: 1
  # Disable
  react/jsx-filename-extension: 0  # unsupported by react-native
  react/require-extension: 0  # deprecated. use eslint-plugin-import instead
