extends: airbnb

parser: babel-eslint

parserOptions:
  ecmaFeatures:
    jsx: true

plugins:
  - react
  - jsx-a11y
  - import
  - flowtype

rules:
  # Enable
  flowtype/define-flow-type: 1
  flowtype/use-flow-type: 1
  # Disable
  react/jsx-filename-extension: 0  # unsupported by react-native
  react/require-extension: 0  # deprecated. use eslint-plugin-import instead
