/* @flow */

// currentCourse
export const SET_CURRENT_COURSE_ID = 'SET_CURRENT_COURSE_ID';
export const COMPLETE_LECTURE = 'COMPLETE_LECTURE';
export const FETCH_COURSE_DETAILS_FAILURE = 'FETCH_COURSE_DETAILS_FAILURE';
export const FETCH_COURSE_DETAILS_START = 'FETCH_COURSE_DETAILS_START';
export const FETCH_COURSE_DETAILS_SUCCESS = 'FETCH_COURSE_DETAILS_SUCCESS';

// Courses
export const FETCH_MY_COURSE_FAILURE = 'FETCH_MY_COURSE_FAILURE';
export const FETCH_MY_COURSE_START = 'FETCH_MY_COURSE_START';
export const FETCH_MY_COURSE_SUCCESS = 'FETCH_MY_COURSE_SUCCESS';
export const FETCH_SNACK_COURSE_FAILURE = 'FETCH_SNACK_COURSE_FAILURE';
export const FETCH_SNACK_COURSE_START = 'FETCH_SNACK_COURSE_START';
export const FETCH_SNACK_COURSE_SUCCESS = 'FETCH_SNACK_COURSE_SUCCESS';
export const UPDATE_COURSE_DOWNLOADED_STATUS = 'UPDATE_COURSE_DOWNLOADED_STATUS';

// Course
export const LOAD_COURSE = 'LOAD_COURSE';
export const PRESS_DOWNLOAD_VIDEO = 'PRESS_DOWNLOAD_VIDEO';
export const BEGIN_DOWNLOAD_VIDEO = 'BEGIN_DOWNLOAD_VIDEO';
export const CANCEL_DOWNLOAD_VIDEO = 'CANCEL_DOWNLOAD_VIDEO';
export const PROGRESS_DOWNLOAD_VIDEO = 'PROGRESS_DOWNLOAD_VIDEO';
export const FINISH_DOWNLOAD_VIDEO = 'FINISH_DOWNLOAD_VIDEO';
export const ERROR_DOWNLOAD_VIDEO = 'ERROR_DOWNLOAD_VIDEO';
export const UPDATE_VIDEO_IN_DEVICE_STATUS = 'UPDATE_VIDEO_IN_DEVICE_STATUS';
export const FINISH_DELETE_VIDEO = 'FINISH_DELETE_VIDEO';

// User
export const FETCH_FB_EMAIL_FAILURE = 'FETCH_FB_EMAIL_FAILURE';
export const FETCH_FB_EMAIL_SUCCESS = 'FETCH_FB_EMAIL_SUCCESS';
export const START_FB_EMAIL_REQUEST = 'START_FB_EMAIL_REQUEST';

export const START_ACT_EMAIL_LOGIN = 'START_ACT_EMAIL_LOGIN';
export const START_ACT_FACEBOOK_LOGIN = 'START_ACT_FACEBOOK_LOGIN';
export const FETCH_ACT_LOGIN_FAILURE = 'FETCH_ACT_LOGIN_FAILURE';
export const FETCH_ACT_LOGIN_SUCCESS = 'FETCH_ACT_LOGIN_SUCCESS';

export const START_ACT_EMAIL_SIGNUP = 'START_ACT_EMAIL_SIGNUP';
export const START_ACT_FACEBOOK_SIGNUP = 'START_ACT_FACEBOOK_SIGNUP';
export const FETCH_ACT_SIGNUP_FAILURE = 'FETCH_ACT_SIGNUP_FAILURE';
export const FETCH_ACT_SIGNUP_SUCCESS = 'FETCH_ACT_SIGNUP_SUCCESS';

export const FINISH_ONBOARDING = 'FINISH_ONBOARDING';

// VideoLecture
export const UPDATE_LECTURE_STATUS_FAILURE = 'UPDATE_LECTURE_STATUS_FAILURE';
export const UPDATE_LECTURE_STATUS_START = 'UPDATE_LECTURE_STATUS_START';
export const UPDATE_LECTURE_STATUS_SUCCESS = 'UPDATE_LECTURE_STATUS_SUCCESS';
export const TOGGLE_PLAY = 'TOGGLE_PLAY';
export const CHANGE_VIDEO_PLAY_SPEED = 'CHANGE_VIDEO_PLAY_SPEED';
export const TOGGLE_FULL_SCREEN = 'TOGGLE_FULL_SCREEN';
export const UPDATE_VIDEO_PROGRESS = 'UPDATE_VIDEO_PROGRESS';
export const SET_CURRENT_LECTURE_ID = 'SET_CURRENT_LECTURE_ID';

// NetInfo
export const MIDDLEWARE_NETINFO = 'MIDDLEWARE_NETINFO';
export const QUEUE_LECTURE_PROGRESS = 'QUEUE_LECTURE_PROGRESS';
export const TRIGGERED_QUEUE_ACTIONS = 'TRIGGERED_QUEUE_ACTIONS';

// ui
export const INIT_APP = 'INIT_APP';

// Premium
export const JOIN_PREMIUM_SUCCESS = 'JOIN_PREMIUM_SUCCESS';
export const JOIN_PREMIUM_FAILURE = 'JOIN_PREMIUM_FAILURE';
export const RESTORE_PREMIUM_SUCCESS = 'RESTORE_PREMIUM_SUCCESS';
export const RESTORE_PREMIUM_FAILURE = 'RESTORE_PREMIUM_FAILURE';
