/* @flow */

// currentCourse
export const COMPLETE_LECTURE = 'COMPLETE_LECTURE';
export const FETCH_COURSE_DETAILS_FAILURE = 'FETCH_COURSE_DETAILS_FAILURE';
export const FETCH_COURSE_DETAILS_START = 'FETCH_COURSE_DETAILS_START';
export const FETCH_COURSE_DETAILS_SUCCESS = 'FETCH_COURSE_DETAILS_SUCCESS';

// Courses

export const PRESS_DOWNLOAD_VIDEO = 'PRESS_DOWNLOAD_VIDEO';
export const BEGIN_DOWNLOAD_VIDEO = 'BEGIN_DOWNLOAD_VIDEO';
export const CANCEL_DOWNLOAD_VIDEO = 'CANCEL_DOWNLOAD_VIDEO';
export const PROGRESS_DOWNLOAD_VIDEO = 'PROGRESS_DOWNLOAD_VIDEO';
export const FINISH_DOWNLOAD_VIDEO = 'FINISH_DOWNLOAD_VIDEO';
export const ERROR_DOWNLOAD_VIDEO = 'ERROR_DOWNLOAD_VIDEO';
export const UPDATE_VIDEO_IN_DEVICE_STATUS = 'UPDATE_VIDEO_IN_DEVICE_STATUS';
export const FINISH_DELETE_VIDEO = 'FINISH_DELETE_VIDEO';

// User
export const FETCH_FB_EMAIL_FAILURE = 'FETCH_FB_EMAIL_FAILURE';
export const FETCH_FB_EMAIL_SUCCESS = 'FETCH_FB_EMAIL_SUCCESS';
export const START_FB_EMAIL_REQUEST = 'START_FB_EMAIL_REQUEST';

export const START_ACT_EMAIL_LOGIN = 'START_ACT_EMAIL_LOGIN';
export const START_ACT_FACEBOOK_LOGIN = 'START_ACT_FACEBOOK_LOGIN';
export const FETCH_ACT_LOGIN_FAILURE = 'FETCH_ACT_LOGIN_FAILURE';
export const FETCH_ACT_LOGIN_SUCCESS = 'FETCH_ACT_LOGIN_SUCCESS';

export const START_ACT_EMAIL_SIGNUP = 'START_ACT_EMAIL_SIGNUP';
export const START_ACT_FACEBOOK_SIGNUP = 'START_ACT_FACEBOOK_SIGNUP';
export const FETCH_ACT_SIGNUP_FAILURE = 'FETCH_ACT_SIGNUP_FAILURE';
export const FETCH_ACT_SIGNUP_SUCCESS = 'FETCH_ACT_SIGNUP_SUCCESS';

export const FINISH_ONBOARDING = 'FINISH_ONBOARDING';

// VideoLecture
export const UPDATE_LECTURE_STATUS_FAILURE = 'UPDATE_LECTURE_STATUS_FAILURE';
export const UPDATE_LECTURE_STATUS_START = 'UPDATE_LECTURE_STATUS_START';
export const UPDATE_LECTURE_STATUS_SUCCESS = 'UPDATE_LECTURE_STATUS_SUCCESS';
export const TOGGLE_PLAY = 'TOGGLE_PLAY';
export const CHANGE_VIDEO_PLAY_SPEED = 'CHANGE_VIDEO_PLAY_SPEED';
export const TOGGLE_FULL_SCREEN = 'TOGGLE_FULL_SCREEN';
export const UPDATE_VIDEO_PROGRESS = 'UPDATE_VIDEO_PROGRESS';

// NetInfo
export const MIDDLEWARE_NETINFO = 'MIDDLEWARE_NETINFO';
export const QUEUE_LECTURE_PROGRESS = 'QUEUE_LECTURE_PROGRESS';
export const TRIGGERED_QUEUE_ACTIONS = 'TRIGGERED_QUEUE_ACTIONS';

// ui

// Premium
export const JOIN_PREMIUM_SUCCESS = 'JOIN_PREMIUM_SUCCESS';
export const JOIN_PREMIUM_FAILURE = 'JOIN_PREMIUM_FAILURE';
export const RESTORE_PREMIUM_SUCCESS = 'RESTORE_PREMIUM_SUCCESS';
export const RESTORE_PREMIUM_FAILURE = 'RESTORE_PREMIUM_FAILURE';

// Purchase
export const PURCHASE_COURSE_SUCCESS = 'PURCHASE_COURSE_SUCCESS';
export const PURCHASE_COURSE_FAILURE = 'PURCHASE_COURSE_FAILURE';
export const RESTORE_COURSE_SUCCESS = 'RESTORE_COURSE_SUCCESS';
export const RESTORE_COURSE_FAILURE = 'RESTORE_COURSE_FAILURE';
