/* @flow */

// currentCourse
export const SET_CURRENT_COURSE_ID = 'SET_CURRENT_COURSE_ID';
export const COMPLETE_LECTURE = 'COMPLETE_LECTURE';
export const FETCH_COURSE_DETAILS_FAILURE = 'FETCH_COURSE_DETAILS_FAILURE';
export const FETCH_COURSE_DETAILS_START = 'FETCH_COURSE_DETAILS_START';
export const FETCH_COURSE_DETAILS_SUCCESS = 'FETCH_COURSE_DETAILS_SUCCESS';

// Courses
export const FETCH_COURSES_LIST_FAILURE = 'FETCH_COURSES_LIST_FAILURE';
export const FETCH_COURSES_LIST_START = 'FETCH_COURSES_LIST_START';
export const FETCH_COURSES_LIST_SUCCESS = 'FETCH_COURSES_LIST_SUCCESS';

// Course
export const LOAD_COURSE = 'LOAD_COURSE';
export const PRESS_DOWNLOAD_VIDEO = 'PRESS_DOWNLOAD_VIDEO';
export const BEGIN_DOWNLOAD_VIDEO = 'BEGIN_DOWNLOAD_VIDEO';
export const PROGRESS_DOWNLOAD_VIDEO = 'PROGRESS_DOWNLOAD_VIDEO';
export const FINISH_DOWNLOAD_VIDEO = 'FINISH_DOWNLOAD_VIDEO';
export const ERROR_DOWNLOAD_VIDEO = 'ERROR_DOWNLOAD_VIDEO';
export const UPDATE_VIDEO_IN_DEVICE_STATUS = 'UPDATE_VIDEO_IN_DEVICE_STATUS';
export const FINISH_DELETE_VIDEO = 'FINISH_DELETE_VIDEO';

// Login
export const FETCH_FB_EMAIL_FAILURE = 'FETCH_FB_EMAIL_FAILURE';
export const FETCH_FB_EMAIL_SUCCESS = 'FETCH_FB_EMAIL_SUCCESS';
export const START_FB_EMAIL_REQUEST = 'START_FB_EMAIL_REQUEST';

export const START_ACT_EMAIL_LOGIN = 'START_ACT_EMAIL_LOGIN';
export const START_ACT_FACEBOOK_LOGIN = 'START_ACT_FACEBOOK_LOGIN';
export const FETCH_ACT_LOGIN_FAILURE = 'FETCH_ACT_LOGIN_FAILURE';
export const FETCH_ACT_LOGIN_SUCCESS = 'FETCH_ACT_LOGIN_SUCCESS';

// VideoLecture
export const UPDATE_LECTURE_STATUS_FAILURE = 'UPDATE_LECTURE_STATUS_FAILURE';
export const UPDATE_LECTURE_STATUS_START = 'UPDATE_LECTURE_STATUS_START';
export const UPDATE_LECTURE_STATUS_SUCCESS = 'UPDATE_LECTURE_STATUS_SUCCESS';
export const PRESS_PLAY = 'PRESS_PLAY';
export const PRESS_SPEED = 'PRESS_SPEED';
export const PRESS_FULL_SCREEN = 'PRESS_FULL_SCREEN';
export const UPDATE_VIDEO_PROGRESS = 'UPDATE_VIDEO_PROGRESS';
export const SET_CURRENT_LECTURE_ID = 'SET_CURRENT_LECTURE_ID';

// NetInfo
export const MIDDLEWARE_NETINFO = 'MIDDLEWARE_NETINFO';
export const SYNC_QUEUE_ACTION = 'SYNC_QUEUE_ACTION';
export const TRIGGER_ACTIONS = 'TRIGGER_ACTIONS';
