/* @flow */
// VideoLecture
export const PRESS_PLAY = 'PRESS_PLAY';
export const PRESS_SPEED = 'PRESS_SPEED';
export const PRESS_FULL_SCREEN = 'PRESS_FULL_SCREEN';
export const VIDEO_PROGRESS = 'VIDEO_PROGRESS';

// Login
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const START_EMAIL_LOGIN = 'START_EMAIL_LOGIN';
export const START_FACEBOOK_LOGIN = 'START_FACEBOOK_LOGIN';
