# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
project 'SharewisActMobile.xcodeproj'

target 'SharewisActMobile' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SharewisActMobile
  pod 'Repro', '2.1.3'

  target 'SharewisActMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
